import type { Metadata } from "next";
import { Alata, Josefin_Sans } from "next/font/google";

import "./globals.css";

const alata = Alata({
  variable: "--font-alata",
  subsets: ["latin"],
  weight: "400",
});

const JosefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alata.variable} ${JosefinSans.variable} min-h-screen max-w-[90rem] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
