import type { Metadata } from "next";
import { Alata, Josefin_Sans } from "next/font/google";

import Header from "@/components/Header";
import HeroSection from "@/components/hero-section";
import InteractiveVR from "@/components/interactive-vr";
import OurCreations from "@/components/our-creation";

import "./globals.css";

const alata = Alata({
  variable: "--font-alata",
  subsets: ["latin"],
  weight: "400",
});

const JosefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alata.variable} ${JosefinSans.variable} min-h-screen max-w-screen-2xl antialiased`}
      >
        <div className="bg-[#E5EAF1] bg-[url(/images/mobile/image-hero.jpg)] bg-cover bg-no-repeat bg-blend-multiply lg:bg-[url(/images/desktop/image-hero.jpg)]">
          <Header />
          <HeroSection />
        </div>
        <InteractiveVR />
        <OurCreations />
        {children}
      </body>
    </html>
  );
}
